# -*- coding: utf-8 -*-
"""Python3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAmpqx4AReY7fpqA7HHkfbdXC1ChI-EY

Exercício 1
"""

def saudar_visitante():
    print("Bem vindo(a) à TechSolutions! Como posso ajudar?")

saudar_visitante()
saudar_visitante()
saudar_visitante()

"""Exercício 2"""

def emitir_som_alarme():
    print("BEEP! BEEP! BEEP! O bolo está pronto!")

emitir_som_alarme()

"""Exercício 3"""

def cartao_boas_festas():
    print("Feliz Natal e um próspero Ano Novo! Que todos os seus desejos se realizem!")

cartao_boas_festas()

"""Exercício 4"""

def executar_danca_robo():
    print("Passo para frente! Giro para a esquerda! Balança os braços!")

executar_danca_robo()
executar_danca_robo()

"""Exercício 5"""

def iniciar_nova_rodada():
    print("--- INÍCIO DA NOVA RODADA ---")
    print("Preparem-se!")

iniciar_nova_rodada()

"""Exercício 6"""

bebida = input("Digite uma bebida de sua escolha: ")

def preparar_bebida():
    print(f"Seu {bebida} está pronto!")

preparar_bebida()

"""Exercício 7"""

nome = input("Digite seu nome: ")

def saudar_visitante_personalizado():
    print(f"Bem-vindo(a), {nome}! Estamos felizes em vê-lo(a)!")

saudar_visitante_personalizado()

"""Exercício 8"""

numero_destino = input("Digite o número destino: ")
mensagem = input("Mensagem: ")

def enviar_sms():
    print(f"Enviando mensagem para: {numero_destino}")
    print(f"{mensagem}")

enviar_sms()

"""Exercício 9"""

def dobrar_ingrediente(ingrediente, quantidade_original):
    print(f"Para {ingrediente}, use {quantidade_original * 2} unidades")

dobrar_ingrediente(ingrediente = "Farinha", quantidade_original = 2)
dobrar_ingrediente(ingrediente = "Açúcar", quantidade_original = 0.5)

"""Exercício 11"""

fruta = input("Digite uma fruta: ")

def fazer_suco(fruta):
  return f"Suco de {fruta} fresco!"

meu_suco = fazer_suco(fruta)

print(meu_suco)

"""Exercício 12"""

def verificar_idade(idade_pessoa, idade_minima):
  if idade_pessoa > idade_minima:
    return True
  else:
    return False

if verificar_idade(idade_pessoa= int(input("Digite a sua idade: ")), idade_minima= int(12)):
  print("Pode entrar!")
else:
  print("Entrada negada.")

"""Exercício 13"""

def calcular_media(nota1, nota2, nota3):
  media = (nota1 + nota2 + nota3) / 3
  return media

resultado_media = calcular_media(nota1 = int(input("Nota 1 = ")), nota2 = int(input("Nota 2 = ")), nota3 = int(input("Nota 3 = ")))
print("O resultado da média é:", resultado_media)

"""Exercício 14"""

def reais_para_dolar(valor_reais, cotacao):
  resultado = valor_reais * cotacao
  return f"O valor de R${valor_reais:.2f} em dólar é de: U${resultado:.2f}"


reais_para_dolar(valor_reais= float(input("Digite o valor: ")), cotacao= float(5.47))

"""Exercício 15"""

def